apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service
  namespace: edge-pi-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsing-service
  template:
    metadata:
      labels:
        app: parsing-service
    spec:
      automountServiceAccountToken: false
      hostNetwork: true  # ⚠️ Make sure port 8890 is not in use on the Pi
      nodeSelector:
        kubernetes.io/hostname: 00000000cf62c74b-iot-pi
      containers:
        - name: fastapi-time-app
          image: ghcr.io/manhar400/supercraft:1.1.0
          imagePullPolicy: IfNotPresent
          args: ["--port", "8890"]  # ✅ Pass the port as an argument
          ports:
            - containerPort: 8890
          volumeMounts:
            - name: external-storage
              mountPath: /external
              readOnly: false  # Set to true if you only need read access
      volumes:
        - name: external-storage
          hostPath:
            path: /var/lib/parsing-service/external  # Path on the host machine
            type: DirectoryOrCreate  # Creates directory if it doesn't exist
      imagePullSecrets:
        - name: ghcr-login