apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service
  namespace: edge-pi-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsing-service
  template:
    metadata:
      labels:
        app: parsing-service
    spec:
      automountServiceAccountToken: false
      hostNetwork: true  # ⚠️ Make sure port 8890 is not in use on the Pi
      nodeSelector:
        kubernetes.io/hostname: 00000000098200f5-iot-pi
      containers:
        - name: fastapi-time-app
          image: ghcr.io/manhar400/govind-iot:1.0.2
          imagePullPolicy: IfNotPresent
          args: ["--port", "8890"]  # ✅ Pass the port as an argument
          ports:
            - containerPort: 8890 # Optional: bind to the host port (not recommended for production)
      imagePullSecrets:
        - name: ghcr-secret


