# workload.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-storage
  namespace: edge-pi-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service
  namespace: edge-pi-2
  labels:
    app: parsing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsing-service
  template:
    metadata:
      labels:
        app: parsing-service
      annotations:
        deployment.version: "v3"  # Changed to force update
    spec:
      automountServiceAccountToken: false
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: 00000000cf62c74b-iot-pi

      initContainers:
      - name: git-clone
        image: alpine/git:latest
        command: ['sh', '-c']
        args:
          - |
            echo "Starting code sync..."
            
            # Configure git with credentials if they exist
            if [ -n "$GIT_USER" ] && [ -n "$GIT_PASS" ]; then
              echo "Configuring git credentials..."
              git config --global credential.helper store
              echo "https://${GIT_USER}:${GIT_PASS}@github.com" > ~/.git-credentials
            fi
            
            # Your repository URL
            REPO_URL="https://github.com/NowPurchase/Arsenal.git"
            
            # Check if code exists
            if [ -d "/code/app" ] && [ "$(ls -A /code/app)" ]; then
              echo "Code exists - trying to update..."
              cd /code/repo && git pull || echo "Update failed - using existing code"
            else
              echo "First time - cloning repository..."
              git clone $REPO_URL /code/repo || exit 1
              mkdir -p /code/app
            fi
            
            # Copy code to app directory
            cp -r /code/repo/* /code/app/
            echo "Code sync complete!"

        env:
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: username
              optional: true  # Makes it optional for public repos
        - name: GIT_PASS
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: password
              optional: true  # Makes it optional for public repos

        volumeMounts:
        - name: code-volume
          mountPath: /code

      containers:
      - name: fastapi-app
        image: ghcr.io/manhar400/my-app-image:1.0
        imagePullPolicy: IfNotPresent
        args: ["--port", "8890"]
        ports:
        - containerPort: 8890

        volumeMounts:
        - name: code-volume
          mountPath: /app/dynamic-code
          subPath: app

        env:
        - name: PYTHONPATH
          value: "/app/dynamic-code:/app"

      volumes:
      - name: code-volume
        persistentVolumeClaim:
          claimName: code-storage

      imagePullSecrets:
      - name: ghcr-secret