apiVersion: v1
kind: Service
metadata:
  name: parsing-service
  namespace: default
spec:
  selector:
    app: parsing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007  # Optional: choose a fixed port or let Kubernetes assign one
  type: NodePort
