apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsing-service
  template:
    metadata:
      labels:
        app: parsing-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: 00000000098200f5-iot-pi     # Replace with your node name
      containers:
        - name: parsing-service
          image: hashicorp/http-echo:latest  # ✅ Test image
          args:
            - "-text=Parsing Service is live"
          ports:
            - containerPort: 5678
