apiVersion: v1
kind: Pod
metadata:
  name: edge-test-app
  namespace: edge-001
spec:
  nodeSelector:
    kubernetes.io/hostname: edge-001  # 👈 Replace this with your actual device hostname
  containers:
    - name: edge-container
      image: nginx:alpine  # 👈 Change to your actual app image
      ports:
        - containerPort: 80
