apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsing-service
  template:
    metadata:
      labels:
        app: parsing-service
    spec:
      hostNetwork: true  # 🔥 This exposes it on the Pi’s real IP (e.g., 192.168.100.29:5678)
      nodeSelector:
        kubernetes.io/hostname: 00000000098200f5-iot-pi
      containers:
        - name: parsing-service
          image: ghcr.io/manhar400/fastapi-time-app:latest
          args:
            - "-text=Parsing Service is live"
          ports:
            - containerPort: 5678
